### ISSUE TITLE
rows and cols not returned from inputProps / useTextField(props) hook for textareas

### ISSUE THREAD

**Issue by manuschillerdev** [adobe/react-spectrum#1178]
# 🐛 Bug Report 

using `useTextField` on a `<textarea/>` does not return `rows` and `cols` as part of  `inputProps`.

## 🤔 Expected Behavior
`rows` and `cols` should be part of  `inputProps` returned by `useTextField(props)` if they were part of `props`.

## 😯 Current Behavior
using `useTextField` on a `<textarea/>` does not return `rows` and `cols` as part of  `inputProps`.

## 💁 Possible Solution

I guess it would be sufficient to add `rows` and `cols` to the definition at https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/textfield/src/useTextField.ts#L70 ?

## 🔦 Context
building a textarea component with `react-aria`

## 💻 Code Sample

https://codesandbox.io/s/delicate-water-gfw05?file=/src/App.js

**Comment by snowystinger** [comment]
Yeah we think it'd be good to add it as textarea only props

**Comment by manuschillerdev** [comment]
That totally makes sense - I‘ll open a PR if you like me to?

**Comment by snowystinger** [comment]
sure, that'd be great! Thanks!

**Comment by manuschillerdev** [comment]
unfortunately I struggle really hard with getting the typings to work, so I need to return this to the core team or any other more experienced ts dev 🤷‍♂️ sorry!!

I think the textarea specific props would be (taken from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2296)

```
        cols?: number;
        dirName?: string;
        disabled?: boolean;
        rows?: number;
        wrap?: string;
```

please let me know if I can help with more input or in any other way.

**Comment by msabramo** [comment]
Would this fix the issue that specifying `rows` for a `Textarea` doesn't work? I just ran into that yesterday and I had to work around it with this ugliness (note I'm using the lowercase "t" HTML `<textarea>`):

```js
            <textarea
              className='spectrum-Textfield spectrum-Textfield--multiline'
              rows={5}
              title="Text to add to images"
              defaultValue={cropSettingsFromRedux.addTextText}
              onChange={evt => cropSettingsDraft.addTextText = evt.target.value}
              data-testid="input-text"
            />
```

**Comment by snowystinger** [comment]
I don't think you'll get the right styles, we use css-modules, so those names would be obfuscated. You'd also miss out on all the behaviors for a text area.
This should be solveable with TS, probably using overload syntax such as in this PR https://github.com/adobe/react-spectrum/pull/1191
I took a quick crack at it, but haven't had time to test it out https://github.com/adobe/react-spectrum/compare/useTextField-types plus both this and the other PR I linked to can't build docs right now. Please see if this meets the needs though.

**Comment by msabramo** [comment]
I'm trying to test this branch and running into some trouble:

```
$ npm install git://github.com/adobe/react-spectrum#useTextField-types --save
...
> react-spectrum-monorepo@2.21.0-beta.0 postinstall /Users/abramowi/workflowz/node_modules/react-spectrum-monorepo
> yarn build:icons && patch-package

yarn run v1.22.10
$ babel-node --presets @babel/env ./scripts/buildIcons.js
/bin/sh: babel-node: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! react-spectrum-monorepo@2.21.0-beta.0 postinstall: `yarn build:icons && patch-package`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the react-spectrum-monorepo@2.21.0-beta.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abramowi/.npm/_logs/2020-12-07T20_44_55_136Z-debug.log
```

**Comment by msabramo** [comment]
I tried:

```
$ npm install -g babel-node
+ babel-node@0.0.1-security
added 1 package in 1.116s
```

but still get the same error about `babel-node` not being found.

**Comment by msabramo** [comment]
Tried:

```
npm install -g @babel/core @babel/node
npm install -g parcel-bundler
```

to solve various errors. Still getting this error though:

```
$ npm install git://github.com/adobe/react-spectrum#useTextField-types --save

> react-spectrum-monorepo@2.21.0-beta.0 postinstall /Users/abramowi/workflowz/node_modules/react-spectrum-monorepo
> yarn build:icons && patch-package

yarn run v1.22.10
$ babel-node --presets @babel/env ./scripts/buildIcons.js
/Users/abramowi/.nvm/versions/node/v12.19.1/lib/node_modules/@babel/core/lib/config/files/plugins.js:152
    throw e;
    ^

Error: Cannot find module '@parcel/babel-plugin-transform-runtime' from '/Users/abramowi/workflowz/node_modules/react-spectrum-monorepo'
    at Function.resolveSync [as sync] (/Users/abramowi/.nvm/versions/node/v12.19.1/lib/node_modules/@babel/core/node_modules/resolve/lib/sync.js:90:15)
    at resolveStandardizedName (/Users/abramowi/.nvm/versions/node/v12.19.1/lib/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Users/abramowi/.nvm/versions/node/v12.19.1/lib/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/Users/abramowi/.nvm/versions/node/v12.19.1/lib/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/Users/abramowi/.nvm/versions/node/v12.19.1/lib/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /Users/abramowi/.nvm/versions/node/v12.19.1/lib/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/Users/abramowi/.nvm/versions/node/v12.19.1/lib/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Users/abramowi/.nvm/versions/node/v12.19.1/lib/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/Users/abramowi/.nvm/versions/node/v12.19.1/lib/node_modules/@babel/core/lib/config/config-descriptors.js:40:19) {
  code: 'MODULE_NOT_FOUND'
}
error Command failed with exit code 1.
```

**Comment by msabramo** [comment]
I found another potential workaround - it might be a bad idea to directly access the DOM like I'm doing and I'd prefer to use refs but I couldn't figure out how to change the `rows` property using refs.

```
            <TextArea
              ...
              data-testid="CropSettings-TextArea"
            />

...

  React.useEffect(() => {
    document.querySelector('[data-testid="CropSettings-TextArea"]').rows = 5;
  });
```

**Comment by msabramo** [comment]
I found another workaround, which simply uses CSS and seems safer than a side effect with DOM manipulation:

```jsx
            <TextArea
              rows={5}

              // CSS hack because rows prop doesn't work - see
              // https://github.com/adobe/react-spectrum/issues/1178
              // Inspired by https://stackoverflow.com/a/57906634
              style={{ lineHeight: '1.5em', height: 'calc(1.5em * 5 + 10px)' }}

                ...
            />
```

**Comment by razvanip** [comment]
I guess a quick fix would be:

in `useTextField`
```
cols: props.cols,
rows: props.rows,
```

or add an extra filter besides `filterDOMProps` called `filterInputProps` but not sure what types to use, the internal ones `TextInputDOMProps` that i guess need to be enhanced with some extra types or the types from `react`.

and merge all the props in the end.

any thoughts ?

**Comment by snowystinger** [comment]
useTextField is both for `input type = text` and `textarea` tags. Unfortunately it's not valid on the input. So we would like to restrict its use.

**Comment by msabramo** [comment]
I just wanted to share that I found a nice way to take my previous hack and extract it from the component where I was using it, using styled-components, so it's not cluttering that component and could be shared with multiple components:

```js
import styled from 'styled-components';
...
// CSS hack because rows prop doesn't work - see
// https://github.com/adobe/react-spectrum/issues/1178
// Inspired by https://stackoverflow.com/a/57906634
const TextAreaWithSpecifiedNumberOfRows = styled(TextArea)`
    lineHeight: 1.5em;
    height: ${props => `calc(1.5em * ${props.rows} + 10px)`};
`;
```

**Comment by benjaminkalk** [comment]
Still no way to set `rows` properly using TextArea component.

**Comment by reidbarber** [comment]
Closing, but we are still open to accepting a contribution here.
