### ISSUE TITLE
Form component is giving error while testing with react testing library render or Enzyme mount function 

### ISSUE THREAD

**Issue by johibkhan2** [adobe/react-spectrum#1277]
Hi,

when i am testing login form(Form component with TextField component) using react testing library render or enzyme mount function, it is throwing below error. so basically it is issue with Form component.Please note that test cases run successfully with html form tag.

TypeError: Cannot read property 'dark' of null

const wrapper = (props = defaultProps) => {
if (!mountedWrapper) {
mountedWrapper = render(<LoginForm {...props} />);
                   ^
}
return mountedWrapper;
};
at $ae471163e3fb08c2a281b1d3e1120f94$export$useColorScheme (node_modules/@react-spectrum/provider/dist/packages/@react-spectrum/provider/src/mediaQueries.ts:23:7)
at Component (node_modules/@react-spectrum/provider/dist/packages/@react-spectrum/provider/src/Provider.tsx:41:25)
at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14803:18)

**Comment by snowystinger** [comment]
Do you wrap all your tests in a Provider? Looks like it might be missing

**Comment by devongovett** [comment]
Closing due to inactivity.
