### ISSUE TITLE
Unable to install and start

### ISSUE THREAD

**Issue by Frikki** [adobe/react-spectrum#1808]
# 🐛 Bug Report 

I follow [the developer guidelines](https://react-spectrum.adobe.com/contribute.html#developing). After successfully cloning and entering the repository directory, I execute:

```shell
yarn install
```

## 🤔 Expected Behavior

Packages should install flawlessly

## 😯 Current Behavior

`yarn install` errors, and subsequently, I am not able to execute `yarn start`.

```shell
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
warning Resolution field "postcss-calc@6.0.2" is incompatible with requested version "postcss-calc@^7.0.1"
warning Resolution field "jsdom@16.3.0" is incompatible with requested version "jsdom@^14.1.0"
warning Resolution field "@babel/core@7.12.10" is incompatible with requested version "@babel/core@7.8.0"
warning Resolution field "@babel/core@7.12.10" is incompatible with requested version "@babel/core@7.8.4"
[2/4] 🚚  Fetching packages...
warning Pattern ["@parcel/plugin@nightly"] is trying to unpack in the same destination "/Users/frikki/Library/Caches/Yarn/v6/npm-@parcel-plugin-2.0.0-nightly.359-0feeace48ad1586a91cd3ea313a1059ec919517d-integrity/node_modules/@parcel/plugin" as pattern ["@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d","@parcel/plugin@2.0.0-nightly.359+6231ca1d"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@parcel/utils@nightly"] is trying to unpack in the same destination "/Users/frikki/Library/Caches/Yarn/v6/npm-@parcel-utils-2.0.0-nightly.359-d5a0d92a62a592acc1d44a2de8a11c2a99ed12a6-integrity/node_modules/@parcel/utils" as pattern ["@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d","@parcel/utils@2.0.0-nightly.359+6231ca1d"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@parcel/node-resolver-core@nightly"] is trying to unpack in the same destination "/Users/frikki/Library/Caches/Yarn/v6/npm-@parcel-node-resolver-core-2.0.0-nightly.1981-54340f7ea2ef9b01bbfdd966607d49e6cfc69bb7-integrity/node_modules/@parcel/node-resolver-core" as pattern ["@parcel/node-resolver-core@2.0.0-nightly.1981+6231ca1d"]. This could result in non-deterministic behavior, skipping.
warning @atom-languages/language-typescript@0.6.2: The engine "atom" appears to be invalid.
warning @atom-languages/language-css@0.44.4: The engine "atom" appears to be invalid.
[3/4] 🔗  Linking dependencies...
warning " > storybook-dark-mode@1.0.4" has unmet peer dependency "@storybook/addons@>= 6.x".
warning " > storybook-dark-mode@1.0.4" has unmet peer dependency "@storybook/api@>= 6.x".
warning " > storybook-dark-mode@1.0.4" has unmet peer dependency "@storybook/components@>= 6.x".
warning " > storybook-dark-mode@1.0.4" has unmet peer dependency "@storybook/core-events@>= 6.x".
warning " > storybook-dark-mode@1.0.4" has unmet peer dependency "@storybook/theming@>= 6.x".
warning " > @react-spectrum/test-utils@3.0.0-alpha.1" has incorrect peer dependency "@testing-library/react@^10.4.9".
[4/4] 🔨  Building fresh packages...
[9/35] ⠄ full-icu
[2/35] ⠄ fsevents
[10/35] ⠄ @parcel/source-map
[11/35] ⠄ @parcel/watcher
warning Error running install script for optional dependency: "/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/fsevents: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/fsevents
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.18.3 | darwin | x64
gyp info find Python using Python version 2.7.16 found at \"/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python\"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/frikki/Library/Caches/node-gyp/12.18.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/frikki/Library/Caches/node-gyp/12.18.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/frikki/Library/Caches/node-gyp/12.18.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command \"/Users/frikki/.nvm/versions/node/v12.18.3/bin/node\" \"/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/fsevents
[-/35] ⠈ waiting...
[13/35] ⠈ sharp
[14/35] ⠈ tree-sitter-typescript
[15/35] ⠈ tree-sitter-css
error /Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/tree-sitter-typescript: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/tree-sitter-typescript
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.18.3 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/tree-sitter-typescript/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/frikki/Library/Caches/node-gyp/12.18.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/frikki/Library/Caches/node-gyp/12.18.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/frikki/Library/Caches/node-gyp/12.18.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/tree-sitter-typescript',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/frikki/.nvm/versions/node/v12.18.3/bin/node" "/Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/frikki/Developer/Projects/adobe/react-spectrum/node_modules/tree-sitter-typescript
```

## 🔦 Context

I can’t run the storybook locally.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System | MacOS 10.15.7 |
| Node | 12.18.3 |
| Yarn | 1.22.10 |

**Comment by snowystinger** [comment]
Have you followed this part of your error `gyp: No Xcode or CLT version detected!` and installed Xcode and the CLT?
https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d

**Comment by Frikki** [comment]
Thank you so much, @snowystinger. The solution provided in your link solved the issue. I should have looked up that particular error myself. However, the issue and the solution here might serve someone else in the future.
