### ISSUE TITLE
Webpack bundling error when used with Gatsby.js

### ISSUE THREAD

**Issue by koraytaylan** [adobe/react-spectrum#2117]
# 🐛 Bug Report 

Webpack bundling error when used with Gatsby.js

## 🤔 Expected Behavior

As mentioned in the documentation, Gatsby should work out of the box.

https://react-spectrum.adobe.com/react-spectrum/ssr.html

## 😯 Current Behavior

```
success open and validate gatsby-configs, load plugins - 0.199s
success onPreInit - 0.039s
success initialize cache - 0.012s
success copy gatsby files - 0.156s
success Compiling Gatsby Functions - 0.468s
success onPreBootstrap - 0.489s
success createSchemaCustomization - 0.002s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.086s
success building schema - 0.475s
success createPages - 0.001s
success createPagesStatefully - 0.078s
info Total nodes: 31, SitePage nodes: 4 (use --verbose for breakdown)
success Checking for changed pages - 0.001s
success update schema - 0.086s
success write out redirect data - 0.003s
success onPostBootstrap - 0.002s
info bootstrap finished - 4.963s
success onPreExtractQueries - 0.006s
success extract queries from components - 1.834s
success write out requires - 0.006s
success run page queries - 0.031s - 1/1 32.09/s
success Caching HTML renderer compilation - 0.001s

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Unexpected token (16:34)

File: node_modules/@react-aria/live-announcer/dist/module.js:16:34

failed Building development bundle - 6.033s
ERROR in ./node_modules/@react-aria/live-announcer/dist/module.js 16:34
Module parse failed: Unexpected token (16:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
|
> export function announce(message, assertiveness, timeout) {
|   if (assertiveness === void 0) {
|     assertiveness = 'assertive';
 @ ./node_modules/@react-aria/combobox/dist/module.js 10:0-54 340:6-14 360:6-14 374:6-14
 @ ./node_modules/@react-spectrum/combobox/dist/module.js 5:0-51 481:6-17 730:6-17
 @ ./node_modules/@adobe/react-spectrum/dist/module.js 18:0-50 18:0-50
 @ ./src/components/layout.js 8:0-76 11:42-53 18:38-46 19:11-23
 @ ./src/pages/index.js 8:0-46 11:42-48
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 21:11-23:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

webpack compiled with 1 error
success Writing page-data.json files to public directory - 0.248s - 1/2 8.07/s
```

## 💁 Possible Solution

In the documentation, there is [a sample repository](https://github.com/devongovett/rsp-gatsby) that I have already checked if I am doing anything out of the ordinary and the only difference seems to be the Gatsby version in that sample repo is 2.24.50 whereas the current version I am trying to use is 3.9.1. Considering a major version increase happened in Gatsby, I think there must be something changed with the webpack configurations on Gatsby side that is causing this.

## 🔦 Context

I am trying to utilize Spectrum React library in a server side rendered context using Gatsby.

## 💻 Code Sample

https://replit.com/@koraytaylan/react-spectrum-gatsby

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.12.0 |
| Browser          | Not relevant |
| Operating System | Mac OS |

**Comment by CanRau** [comment]
Not sure it's the same but in my [Vite](https://vitejs.dev/) with [vite-plugin-ssr](https://vite-plugin-ssr.com/) React app I'm getting

```
font-style:var(--spectrum-global-font-style-regular,normal)}._spectrum-Body--italic_60105{
                                                            ^
SyntaxError: Unexpected token '.'
    at new Script (node:vm:100:7)
    at p._moduleCompile (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/jiti/dist/v8cache.js:2:3154)
    at Module.o._compile (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/jiti/dist/v8cache.js:2:2705)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at n (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/jiti/dist/v8cache.js:2:2472)
    at Object.<anonymous> (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/@react-spectrum/provider/dist/main.js:40:1)
    at Module.o._compile (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/jiti/dist/v8cache.js:2:2778)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at n (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/jiti/dist/v8cache.js:2:2472)
    at Object.<anonymous> (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/@react-spectrum/overlays/dist/main.js:25:5)
    at Module.o._compile (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/jiti/dist/v8cache.js:2:2778)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at n (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/jiti/dist/v8cache.js:2:2472)
    at Object.<anonymous> (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/@react-spectrum/tooltip/dist/main.js:11:5)
    at Module.o._compile (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/jiti/dist/v8cache.js:2:2778)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at n (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/jiti/dist/v8cache.js:2:2472)
    at Object.<anonymous> (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/@react-spectrum/actiongroup/dist/main.js:9:5)
    at Module.o._compile (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/jiti/dist/v8cache.js:2:2778)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at n (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/jiti/dist/v8cache.js:2:2472)
    at Object.<anonymous> (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/@adobe/react-spectrum/dist/main.js:6:20)
    at Module.o._compile (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/jiti/dist/v8cache.js:2:2778)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at nodeRequire (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/vite/src/node/ssr/ssrModuleLoader.ts:160:15)
    at ssrImport (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/vite/src/node/ssr/ssrModuleLoader.ts:93:14)
    at eval (/pages/_default/_default.page.server.tsx:9:31)
    at instantiateModule (/Users/Can/Projects/Can/canrau.com_vite-template-react-plus/node_modules/vite/src/node/ssr/ssrModuleLoader.ts:135:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by snowystinger** [comment]
Closing, we have some documentation around this now https://react-spectrum.adobe.com/react-spectrum/ssr.html#gatsby

We can reopen if there's still an issue.
