### ISSUE TITLE
`useNumberField()` with `onChange` causes React warning: Cannot update a component while rendering a different component

### ISSUE THREAD

**Issue by starbugs** [adobe/react-spectrum#2741]
# 🐛 Bug Report 

`useNumberField()` with `onChange` causes bad `setState()` call when using the up and down arrow keys on the keyboard to change the number value.

I tested this by following the documentation at https://react-spectrum.adobe.com/react-aria/useNumberField.html#controlled.

## 🤔 Expected Behavior

`onChange` should not be called while rendering. 

## 😯 Current Behavior

`onChange` is called while `NumberField` is rendering when hitting the up/down arrow key, since useSpinButton() along with some other functions appear to call `onChange()` during rendering (indirectly via `useNumberFieldState()`.  React issues a warning:

```Warning: Cannot update a component (`Example`) while rendering a different component (`NumberField`). To locate the bad setState() call inside `NumberField`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at NumberField (http://localhost:9000/bundle.js:42963:77)
    at Example (http://localhost:9000/bundle.js:42919:56)```

In a simple example case, nothing else happens and the app appears to work correctly.

In a real application, follow-up errors due to hooks called in the wrong places happen.

## 💁 Possible Solution

I think `onChange` should be wrapped in a `useEffect()` call so that I have a chance to make state changes for the parent component outside the rendering phase.

## 🔦 Context

Trying to have a sidebar with a couple of number fields where the user can change numbers and affect properties of an object displayed in a main view.

## 💻 Code Sample

https://github.com/starbugs/react-aria-test

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | numberfield 3.1.1 |
| Browser          | Chrome |
| Operating System | macOS |

## 🧢 Your Company/Team

N/A

## 🕷 Tracking Issue (optional)

N/A

**Comment by snowystinger** [comment]
Thanks! This will be fixed in our next release.
closing as a duplicate of https://github.com/adobe/react-spectrum/issues/2418
