### ISSUE TITLE
Testing library shows "act" warning with react-aria's useButton

### ISSUE THREAD

**Issue by manelsanz** [adobe/react-spectrum#2755]
Hi, after ask for it in StackOverflow and Github discussions of both libraries with no luck, finally I decided to put an issue here. I hope someone can help me, thank you. I'm using Windows 10 and create-react-app.
### Library versions
````javascript
"react-aria": "3.12.0",
"react-dom": "17.0.2",
"react-scripts": "4.0.3",
"@testing-library/jest-dom": "5.16.1",
"@testing-library/react": "12.1.2",
"@testing-library/react-hooks": "7.0.2",
"@testing-library/user-event": "12.1.3",
````
Tried also with user-event 13.5.0 and 14.0.0.beta-8 versions  

### Minimum code to reproduce the warning (the test passes)

````javascript
import React, { useRef } from 'react';
import { useButton } from 'react-aria';
import userEvent from '@testing-library/user-event';

import { render, screen } from '@testing-library/react';

export const Button = (props: { onPress: () => void; children: React.ReactChild }) => {
  const ref = useRef<HTMLButtonElement>(null);
  const { buttonProps } = useButton(props, ref);
  const { children } = props;

  return (
    <button {...buttonProps} ref={ref}>
      {children}
    </button>
  );
};

describe('Atoms/Button', () => {
  const handleOnClick = jest.fn();

  it('should execute the callback function onClick', () => {
    render(<Button onPress={handleOnClick}>test me</Button>);

    const testButton = screen.getByRole('button');
    expect(testButton).toBeInTheDocument();
    expect(testButton).toHaveTextContent('test me');

    userEvent.click(testButton);

    expect(handleOnClick).toHaveBeenCalledTimes(1);
  });
});
````

### Full console output
````javascript
 PASS  src/components/_global/atoms/Button/tests/Button.test.tsx
  Atoms/Button
    ✓ should execute the callback function onClick (114 ms)

  console.error
    Warning: An update to Button inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at Button (/PROJECT_PATH/components/_global/atoms/Button/tests/Button.test.tsx:10:15)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:24064:9)
      at setPressed (node_modules/react-dom/cjs/react-dom.development.js:16135:9)
      at triggerPressEnd (node_modules/@react-aria/interactions/dist/packages/@react-aria/interactions/src/usePress.ts:179:7)
      at Document.onMouseUp (node_modules/@react-aria/interactions/dist/packages/@react-aria/interactions/src/usePress.ts:517:11)
      at Document.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.274 s
````

**Comment by snowystinger** [comment]
Closing this one until we determine if there actually is a bug while we're discussing over here: https://github.com/adobe/react-spectrum/discussions/2743
