### ISSUE TITLE
Error when compiling 

### ISSUE THREAD

**Issue by j7cb1** [adobe/react-spectrum#3066]
# 🐛 Bug Report 

```
(node:36369) UnhandledPromiseRejectionWarning: /home/mono-webserver/node_modules/@react-aria/interactions/dist/main.js:558
    ref = ref ?? newRef;
               ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/mono-webserver/node_modules/@nextui-org/react/cjs/button/button.js:1:642)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
(node:36369) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36369) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:36369) UnhandledPromiseRejectionWarning: /home/mono-webserver/node_modules/@react-aria/interactions/dist/main.js:558
    ref = ref ?? newRef;
               ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/mono-webserver/node_modules/@nextui-org/react/cjs/button/button.js:1:642)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
(node:36369) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

> Build error occurred
/home/mono-webserver/node_modules/@react-aria/interactions/dist/main.js:558
    ref = ref ?? newRef;
               ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/mono-webserver/node_modules/@nextui-org/react/cjs/button/button.js:1:642)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
  type: 'SyntaxError'
}
```

## 🤔 Expected Behavior

Should just compile 

## 😯 Current Behavior

Haven't found much online and It's still not compiling

**Comment by snowystinger** [comment]
looks like https://github.com/adobe/react-spectrum/issues/2857 ?

**Comment by devongovett** [comment]
Looks like nextui needs to update to a newer version: https://github.com/nextui-org/nextui/blob/3d9549c3a2654abf584ea8e4ebe4df3f6508606d/packages/react/package.json#L63

cc. @jgarciadev
