### ISSUE TITLE
React warning thrown when attempting to reset a controlled async combobox.

### ISSUE THREAD

**Issue by joshua-harrison-2011** [adobe/react-spectrum#3153]
# 🐛 Bug Report 

I'm using the second AsyncLoadingExample here https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#asynchronous-loading.  I then add an action button with the intent of resetting the combobox:

```
<ActionButton onPress={() => {
        list.removeSelectedItems();
        list.setFilterText('');
}}> Reset </ActionButton>
```

While this does clear the combobox, it produces the warning: `WARN: A component changed from controlled to uncontrolled.`. 

## 🤔 Expected Behavior

There should be no warning.

## 😯 Current Behavior

```
react_devtools_backend.js:4026 WARN: A component changed from controlled to uncontrolled. 
    at ComboBoxBase (http://localhost:3000/static/js/bundle.js:55827:34)
    at $2289f375e813f187$var$ComboBox (http://localhost:3000/static/js/bundle.js:55814:85)
...
```

## 💁 Possible Solution

?

## 🔦 Context

This is a minor inconvenience.  I'm filing at the request of one of the Spectrum developers who said:

```
it's possible this might be a bug in useAsyncList/useListData, I'll need to dig some more. At the very least, removeSelectedItems shouldn't be throwing that warning it at all possible, mind filing an issue for this?
```

## 💻 Code Sample

https://codesandbox.io/s/falling-star-r9pf1z?file=/package.json

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.17.0 | 
| Browser          | Chrome |
| Operating System | Mac |

**Comment by LFDanLu** [comment]
Thanks for filing this, helps keep this on our radar for investigation!

**Comment by snowystinger** [comment]
I think the problem is here, because we're taking the control of the selectedKeys out of the users hands and we don't know if it's controlled or not https://github.com/adobe/react-spectrum/blob/85764ff79960a9e71b74456c506d37227f2d7a4b/packages/%40react-stately/data/src/useListData.ts#L250

maybe the function `removeSelectedItems` should either not change the selectedKeys or the function should take a `newSelectedKeys` argument
