### ISSUE TITLE
[`@react-aria/dnd`]:  `window is not defined` using `useDrag` with SSR

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [adobe/react-spectrum#3615]
# 🐛 Bug Report 

Using `useDrag` (`@react-aria/dnd`) fails to work in Server Side Rendering

## 🤔 Expected Behavior

It should correctly work even with SRR

## 😯 Current Behavior

When using the `useDrag` hook in a Next.js application (with SSR), on page load the app crashes. In development the error modal opens: 

![image](https://user-images.githubusercontent.com/53900565/194753362-9845bfb6-74e4-4783-a170-817f46334f33.png)

**With stack trace in the terminal:**
```txt
ReferenceError: window is not defined
    at $4620ae0dc40f0031$var$mapModality (/home/Projects/work/snailycad/snaily-cadv4/node_modules/@react-aria/dnd/dist/main.js:92:53)
    at $4620ae0dc40f0031$export$49bac5d6d4b352ea (/home/Projects/work/snailycad/snaily-cadv4/node_modules/@react-aria/dnd/dist/main.js:96:12)
    at $dc204e8ec58447a6$export$7941f8aafa4b6021 (/home/Projects/work/snailycad/snaily-cadv4/node_modules/@react-aria/dnd/dist/main.js:2846:20)
    at Draggable (webpack-internal:///../../packages/ui/dist/components/dnd/draggable.mjs:12:93)
    at renderWithHooks (/home/Projects/work/snailycad/snaily-cadv4/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/home/Projects/work/snailycad/snaily-cadv4/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/home/Projects/work/snailycad/snaily-cadv4/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/Projects/work/snailycad/snaily-cadv4/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/Projects/work/snailycad/snaily-cadv4/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/Projects/work/snailycad/snaily-cadv4/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
error - ReferenceError: window is not defined
    at $4620ae0dc40f0031$var$mapModality (/home/Projects/work/snailycad/snaily-cadv4/node_modules/@react-aria/dnd/dist/main.js:92:53)
    at $4620ae0dc40f0031$export$49bac5d6d4b352ea (/home/Projects/work/snailycad/snaily-cadv4/node_modules/@react-aria/dnd/dist/main.js:96:12)
    at $dc204e8ec58447a6$export$7941f8aafa4b6021 (/home/Projects/work/snailycad/snaily-cadv4/node_modules/@react-aria/dnd/dist/main.js:2846:20)
    at Draggable (webpack-internal:///../../packages/ui/dist/components/dnd/draggable.mjs:12:93)
    at renderWithHooks (/home/Projects/work/snailycad/snaily-cadv4/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/home/Projects/work/snailycad/snaily-cadv4/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/home/Projects/work/snailycad/snaily-cadv4/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/Projects/work/snailycad/snaily-cadv4/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/Projects/work/snailycad/snaily-cadv4/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/Projects/work/snailycad/snaily-cadv4/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12) {
  page: '/dispatch'
}
```

## 💁 Possible Solution

Check if `window` is defined here: 
https://github.com/adobe/react-spectrum/blob/227f79e33d9734bbc136c22160327b0a988d2908/packages/%40react-aria/dnd/src/utils.ts#L65

## 💻 Code Sample

[codesandbox](https://codesandbox.io/p/github/Dev-CasperTheGhost/ssr-react-aia-dnd/draft/vibrant-panna?file=%2Fpages%2Findex.tsx&workspace=%257B%2522activeFileId%2522%253A%2522cl919iryl0001lth02pdr8kfm%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522cl919jg4p00dd2a693g23ejjq%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl919j0l800at2a69d26hgkd5%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl919iz7f007f2a693uck8yfr%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| "@react-aria/dnd" | "^3.0.0-rc.0" |
| Browser          | Firefox
| Operating System | WSL2  |

**Comment by Dev-CasperTheGhost** [comment]
Closed by #3616
