### ISSUE TITLE
`Select` SSR `tabIndex` mismatch

### ISSUE THREAD

**Issue by LFDanLu** [adobe/react-spectrum#3758]
### Discussed in https://github.com/adobe/react-spectrum/discussions/3755

<div type='discussions-op-text'>

<sup>Originally posted by **duckies** November 16, 2022</sup>
Hello, I have hit a wall trying to figure out why the `Select` Tailwind example is causing console warnings about `tabindex` under Nextjs's SSR. I have created a Codesandbox following the example as closely as possible.

## Error
```
Warning: Prop `tabIndex` did not match. Server: "-1" Client: "0"
    at input
    at div
    at $bdd25dc72710631f$export$cbd84cdb2e668835 (webpack-internal:///./node_modules/@react-aria/select/dist/module.js:202:18)
    at div
    at Select (webpack-internal:///./components/Select.tsx:27:78)
    at div
    at IndexPage
    at $704cf1d3b684cc5c$export$9f8ac96af4b1b2ae (webpack-internal:///./node_modules/@react-aria/ssr/dist/module.js:23:64)
    at Application (webpack-internal:///./pages/_app.tsx:11:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:3325)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:6707)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:60:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:173:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:346:11)
```

## [Codesandbox Reproduction](https://codesandbox.io/s/react-aria-next-js-ssr-select-prop-mismatch-dtnyc5?file=/components/Select.tsx)

- I was following the [Tailwind CSS](https://codesandbox.io/s/hardcore-moon-xzc4r?file=/src/Select.tsx) example linked from [useSelect — React Aria](https://react-spectrum.adobe.com/react-aria/useSelect.html#styled-examples).
- The issue is the same regardless of using the nightly builds found in the example (`react-aria@3.20.1-nightly.3567` and `react-stately@3.18.1-nightly.3567`) or latest stable versions (`react-aria@3.21.0` and `react-stately@3.19.0`), so I left the reproduction at the latter.
- The error is not consistent on every reload. Trying to interact with the `Select` as quickly as possible after reloading more reliably causes the warning.
</div>

**Comment by LFDanLu** [comment]
This seems to be due to a modality check in [HiddenSelect](https://github.com/adobe/react-spectrum/blob/44d7ebc49c2edaf04c88ed345b9c04a918bf91a9/packages/%40react-aria/select/src/HiddenSelect.tsx#L78), I was able to reproduce consistently if I moved my mouse in the sandbox iframe while the example loaded. We could add a [useIsSSR](https://github.com/adobe/react-spectrum/blob/44d7ebc49c2edaf04c88ed345b9c04a918bf91a9/packages/%40react-aria/ssr/src/SSRProvider.tsx#L91) to that HiddenSelect code to have consistent tabindex for SSR
