### ISSUE TITLE
useComboBox not syncing state correctly and incorrectly selects current selection on tab out of popup

### ISSUE THREAD

**Issue by binaryartifex** [adobe/react-spectrum#4016]
# 🐛 Bug Report 
The state manager does not immediately show results via popup when a network request returns a response. At first I thought this was a bug related to me applying conditional logic with the useAsyncList load function, whereby a fetch should only be done after a certain amount of characters have been input. This predicate had to be done within the async load function because i needed access to the filterText, trying to hold the text in external state and manage that and the useAsyncState quickly turned into a hot mess of useCallbacks and infinite loops. However im finding the same issue present using react-query. 

Extending on this, when a list does appear (the state seems to be one step behind the render itself - a list is loaded into memory on first fetch, nothing appears, type another character, and suddenly the popup appears), when navigating the list using the up and down arrows, the focused element should not be 'selected' when attempting to tab out of the field.

## 🤔 Expected Behavior
I should be able to apply a predicate within any async function generating a response for the useComboBox (and by extension its state hook) and it should appear on first instance of an iterable list. When navigating said list via up and down arrows, tabbing should not 'select' the current focused element, it should just exit and clear the state. 

## 😯 Current Behavior
If the component with the useComboBox does not render an initial list, when it does receive a list, it does not immediately render it. Follow up filterTexts will make it render however, but not on the initial passing of whatever predicate prevented fetching in the first place. also in this instance, tabbing away from a focused element selects it -creating a redundant network request (it clearly shows which item i wish to select in the dropdown, any action moving forward should be whatever action i assign the list item, in this case, a redirect). So at present when the item i wish to redirect too is available in the search list, i have to currently click it, which performs another search request returning just that particular item, and then another followup click to finally redirect.

## 🔦 Context
Im trying to create an asynchronous search field that functions in much the same way user experience wise as the amazon search field, for context. it provides a dropdown of results, navigable with up and down arrows, tabbing doesnt mistakenly select one and pressing space or enter automatically navigates to that page and clears the state of the field on redirect. With that out of the way...

## 💻 Code Sample

This link is almost exactly the same as @devongovett's example of an async autocomplete. The only thing ive changed is added in a predicate within the async load function. All the above concerns are demonstratable. 

[example code](https://codesandbox.io/s/musing-sound-vix0w9?file=/src/App.tsx)

1. type in 'a'
2. predicate is passed (greater than or equal to 1 character) and a request is made, however no popup shows with results
3. type in "r" and popup with names finally shows, despite predicate passing and results recieved in the previous render
4. using up down arrows, focus on any item and press tab, instead of closing and clearing the field and its state, the focused item is incorrectly selected, however the escape key seems to work in in this instance.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria | 3.22.0
| react-stately | 3.20.0
| Browser          | Chrome@^109
| VSCode | v1.75
| Node | 16.14.2
| Operating System | Windows 11

**Comment by binaryartifex** [comment]
EDIT: On further looking into the issue, it appears the useComboBox issue of no initial render for empty collections is an ongoing issue - #2333. The advice given here is to provide the allowsEmptyCollections flag on the useComboBoxState and to prevent an empty box appearing until a response is received, provide a secondary predicate to the popover rendering. Ive added the following changes to the above codesandbox reference [here](https://codesandbox.io/s/musing-sound-vix0w9?file=/src/Autocomplete.tsx)

```typescript
  let state = useComboBoxState({
    ...props,
    allowsEmptyCollection: true,
    defaultFilter: contains
  });
```

and added a secondary predicate to popover render

```typescript
      {Boolean(state.isOpen && state.collection.size > 0) && (
        <Popover
          popoverRef={popoverRef}
          triggerRef={inputRef}
          state={state}
          isNonModal
          placement="bottom start"
        >
          <ListBox
            {...listBoxProps}
            listBoxRef={listBoxRef}
            state={state}
            loadingState={props.loadingState}
            onLoadMore={props.onLoadMore}
          />
        </Popover>
      )}
```

As a result, this (almost) gets me exactly to where my initial use case required. unfortunately, the check against the collection size throws an Error (as is demonstrated in the code sandbox link - `Cannot read properties of null (reading 'contains')`

**Comment by binaryartifex** [comment]
Alright i seem to have momentarily fixed the `Cannot read properties of null (reading 'contains')` error. By manually creating a ref for the popover and passing that to the popover component and the combobox state, the error no longer appears. I think there is a 'chicken/egg' issue somewhere with regard to what renders first - this becomes evident when the state.collection predicate is used to render the popover...credit to @drivasperez from issue #3787 for the idea. Codesandbox with below solution [here](https://codesandbox.io/s/musing-sound-vix0w9?file=/src/Autocomplete.tsx:673-2364). Its not pretty, but it seems to hold up for now...

```typescript
export function Autocomplete<T extends object>(props: AutocompleteProps<T>) {
  const [popoverRef] = React.useState<HTMLDivElement>(
    document.createElement("div")
  );

  let { contains } = useFilter({ sensitivity: "base" });
  let state = useComboBoxState({
    ...props,
    allowsEmptyCollection: true,
    defaultFilter: contains
  });

  let inputRef = React.useRef(null);
  let listBoxRef = React.useRef(null);
  //let popoverRef = React.useRef(null);

  let { inputProps, listBoxProps, labelProps } = useComboBox(
    {
      ...props,
      inputRef,
      listBoxRef,
      popoverRef: { current: popoverRef }
    },
    state
  );

  return (
    <Box display="inline-block" position="relative">
      <FormLabel {...labelProps}>{props.label}</FormLabel>
      <InputGroup>
        <InputLeftElement>
          <Search2Icon color="gray.500" />
        </InputLeftElement>
        <Input {...inputProps} ref={inputRef} size="md" />
        <InputRightElement>
          {props.loadingState === "loading" ||
          props.loadingState === "filtering" ? (
            <Spinner color="blue.400" size="sm" />
          ) : null}
        </InputRightElement>
      </InputGroup>
      {Boolean(state.isOpen && state.collection.size) && (
        <Popover
          popoverRef={{ current: popoverRef }}
          triggerRef={inputRef}
          state={state}
          isNonModal
          placement="bottom start"
        >
          <ListBox
            {...listBoxProps}
            listBoxRef={listBoxRef}
            state={state}
            loadingState={props.loadingState}
            onLoadMore={props.onLoadMore}
          />
        </Popover>
      )}
    </Box>
  );
}
  
```

**Comment by LFDanLu** [comment]
Glad that you were able to get it all working! As for the selection on tab, we could look into modifying this [line](https://github.com/adobe/react-spectrum/blob/020a0a53d53140f5561e5a5b68ad73a9660eca0d/packages/%40react-stately/combobox/src/useComboBoxState.ts#L303) so that it only resets the input value and closes the trigger, but the git blame seems to indicate that going that route had some issues with the allowCustomValue/fully controlled experience

**Comment by binaryartifex** [comment]
@LFDanLu cheers for the reply, yeah it took a hot minute, but just like my sex life, persistence is the key haha. there is still the question over the rather unintuitive way of how the popoverRef is propagated to get it working the first place...

```typescript
  const [popoverRef] = React.useState<HTMLDivElement>(
    document.createElement("div")
  );
```

As for the tab selection, i think its deceptive at best and almost a bug at worst. When in the history of keyboard navigation has a tab been used to confirm a selection? I do feel like its something worth revisiting. I understand the usecase for combobox however for something that i thought would be a simple endeavor to create a searchfield that responds with a list of navigation links from an api, with the amount of overriding necessary, perhaps combobox isn't entirely fit for purpose for such a use case? It would be awesome if someone could provide a working demo attached to the useSearchField or useComboBox documentation in the react-aria docs showing such a use case...cause hot damn i certainly underestimated the hurdles i was going to get punched in the face with trying to get it working....

**Comment by LFDanLu** [comment]
Something we can revisit for sure. For this use case our SearchAutocomplete pattern is more appropriate I'd imagine, but that hook and its corresponding component is still in alpha and is heavily based off our combobox hooks so we can look into these changes there.

**Comment by devongovett** [comment]
The [native combobox implementation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) in Chrome and Firefox both select on tab. So does the [ARIA example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/).

**Comment by binaryartifex** [comment]
@devongovett indeed it does. I stand corrected. As @LFDanLu suggested, i wasn't aware of a SearchAutocomplete component in the works so i'll definitely be watching out for its initial release as perhaps a better alternative for this particular use case

**Comment by snowystinger** [comment]
@binaryartifex we have an alpha out if you'd like to give it a try https://www.npmjs.com/package/@react-spectrum/autocomplete?activeTab=versions
It doesn't have docs yet, but you could look around in the source for stories and pre-docs

**Comment by binaryartifex** [comment]
@snowystinger yeah mate so ive got the autocomplete up and running and it appears it suffers from the exact same issues. Building straight from the async demo provided in the docs ->

- Using useAsyncList, provide a predicate that blocks network request within the load function (ie. min of 3 characters), return empty array by default

When the predicate is met, the request is made, a response is recieved, however nothing is rendered. any characters added to the filterText variable after the initial request will trigger the render.

- Set the allowsEmptyCollection predicate to true for the useComboBoxState.

At this point, when the field is active with the first character, an unwanted empty box will render beneath the field in accordance with whatever popover styling has been applied. However in this instance, it will render the initial network response properly.

- At this point the logical step i would of thought, is to add a predicate against the render of the popover itself, using the size of the collection to determine if it should appear. So i have a predicate where if the state is set to open and the collection size is greater than 0, render the popover with results.

At this point the following error is thrown

```
Uncaught TypeError: Cannot read properties of null (reading 'contains')
    at ariaHideOutside.ts:97:64
    at Array.some (<anonymous>)
    at MutationObserver.<anonymous> (ariaHideOutside.ts:97:46)
```

The only way to avoid this error, is to manually create the popover ref and inject it where its required 
`const [popoverRef] = useState<HTMLDivElement>(document.createElement("div"));`

This popover fix/hack to me kinda insinuated async 'empty by default' isn't 100% on the money just yet...i would expect that all thats required for an initially empty async list that conditionally performs a network request would at most, just require the allowsEmptyCollection flag, and would render the results in the absence of an empty box, on initial response.

**Comment by mryechkin** [comment]
> Alright i seem to have momentarily fixed the `Cannot read properties of null (reading 'contains')` error. By manually creating a ref for the popover and passing that to the popover component and the combobox state, the error no longer appears. I think there is a 'chicken/egg' issue somewhere with regard to what renders first - this becomes evident when the state.collection predicate is used to render the popover...credit to @drivasperez from issue #3787 for the idea. Codesandbox with below solution [here](https://codesandbox.io/s/musing-sound-vix0w9?file=/src/Autocomplete.tsx:673-2364). Its not pretty, but it seems to hold up for now...

@binaryartifex thanks for this solution - it fixed my issue with the `Cannot read properties of null (reading 'contains')` error, with one caveat.

I had to make a slight modification to make it work in an SSR environment (Next 13.2 in my case):

```jsx
const [popoverRef, setPopoverRef] = useState(null);

  useEffect(() => {
    setPopoverRef(document.createElement('div'));
  }, []);
```

**Comment by arbKow** [comment]
@mryechkin do You have issues with popover appearing in different position after switching to Your suggestion? Don;t know why but when I switched to 'fix approach' my popover appears next to my element rather than under it.
```tsx
export function ComboBox<T extends object>(props: ComboBoxProps<T>) {
  const [popoverRef, setPopoverRef] = useState<HTMLDivElement | null>(
    null
  );
  let { contains } = useFilter({ sensitivity: 'base' });
  let state = useComboBoxState({
    ...props,
    defaultFilter: contains,
  });

  let inputRef = useRef(null);
  let listBoxRef = useRef(null);
  // let popoverRef = useRef(null);
  let wrapperRef = useRef<HTMLDivElement>(null);
  let buttonRef = useRef(null);

  useEffect(() => {
    setPopoverRef(document.createElement('div'));
  }, []);

  let {
    inputProps,
    listBoxProps,
    buttonProps: triggerProps,
  } = useComboBox(
    {
      ...props,
      inputRef,
      listBoxRef,
      buttonRef,
      popoverRef: { current: popoverRef },
    },
    state
  );

  let { buttonProps } = useButton(triggerProps, buttonRef);

  return (
    <div className={styles.wrapper} ref={wrapperRef}>
      <div className={styles.inputGroup}>
        <button
          ref={buttonRef}
          {...buttonProps}
          className={styles.iconButton}
        >
          <Icon
            iconSource={IconSearch}
            name="Search for interviewer"
          />
        </button>
        <input
          {...inputProps}
          ref={inputRef}
          className={styles.input}
        />
      </div>
      {Boolean(state.isOpen && state.collection.size) && (
        <Popover
          popoverRef={{ current: popoverRef }}
          triggerRef={wrapperRef}
          state={state}
          isNonModal
          placement="bottom"
          widthPx={wrapperRef.current?.offsetWidth ?? 150}
        >
          <ListBox
            {...listBoxProps}
            listBoxRef={listBoxRef}
            state={state}
          />
        </Popover>
      )}
    </div>
  );
}
```
