### ISSUE TITLE
FocusScope autoFocus Error: Uncaught TypeError: Cannot read properties of undefined (reading 'previousElementSibling')]

### ISSUE THREAD

**Issue by AndyOGo** [adobe/react-spectrum#4186]
# 🐛 Bug Report 

For `<FocusScope autoFocus>` the `scope` is not checked for `undefined`, which yields this error on mount (e.g.g with enzyme).

> TypeError: Cannot read properties of undefined (reading 'previousElementSibling')]

- https://github.com/adobe/react-spectrum/blob/1e473d38528d415379dfea63958ffc1d04900886/packages/%40react-aria/focus/src/FocusScope.tsx#L130
- https://github.com/adobe/react-spectrum/blob/1e473d38528d415379dfea63958ffc1d04900886/packages/%40react-aria/focus/src/FocusScope.tsx#L468-L474
- https://github.com/adobe/react-spectrum/blob/1e473d38528d415379dfea63958ffc1d04900886/packages/%40react-aria/focus/src/FocusScope.tsx#L452-L453

## 🤔 Expected Behavior

`scope` should be checked.

## 😯 Current Behavior

`scope` is accessed without being checked for it's existence.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by jameshfisher** [comment]
@AndyOGo can you point me to where this was fixed? I'm still seeing it on latest `@react-aria/focus` (v3.12.1).

**Comment by jameshfisher** [comment]
Current `main` looks like it still has an unsafe assumption that `scope[0]` exists: https://github.com/adobe/react-spectrum/blob/a30e1bf810e03f4a4457c788c1a1315423567e96/packages/%40react-aria/focus/src/FocusScope.tsx#L453

**Comment by LFDanLu** [comment]
Mind elaborating in what scenarios you are seeing this issue? We can certainly adjust that line to make sure `scope[0]` exists but it would be good to figure out what call to `focusFirstInScope` is breaking.

**Comment by karimhossenbux** [comment]
Also seeing this error using the Modal.

I wanted to use <Transition> from Headless UI to animated the modal and overlay opening and closing.

I had to get ride of the conditional rendering on state.isOpen (see ModalTrigger component here https://react-spectrum.adobe.com/react-aria/useModalOverlay.html#example)

Removing `state.isOpen` fix the animation and works fine opening and closing the modal. But first time we close the modal seeing this error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'previousElementSibling')
    at $9bf71ea28793e738$var$focusFirstInScope (FocusScope.tsx:453:27)
    at FocusScope.tsx:367:13
```

Note that I also to do this hack to get of another error message https://github.com/adobe/react-spectrum/issues/3787#issuecomment-1413900016

**Comment by LFDanLu** [comment]
@karimhossenbux would you happen to have a sample repo or code sandbox that you could share to help us reproduce the issue? I'm also surprised you still need the workaround from https://github.com/adobe/react-spectrum/issues/3787#issuecomment-1413900016, what version of react0aria are you on?

**Comment by karimhossenbux** [comment]
@LFDanLu we are using `v3.25.0`.

I've replicated the issue here: https://codesandbox.io/p/sandbox/musing-diffie-4ywcyk?file=%2Fsrc%2Fcomponents%2Fmodal.tsx%3A43%2C27

You'll see that closing the modal will throw the error `Uncaught TypeError: Cannot read properties of undefined (reading 'previousElementSibling')`

We are explicitely not using the conditional rendering on `state.isOpen` to have the opening/closing animation.

Thank you for looking into that 🙌

**Comment by LFDanLu** [comment]
Thanks for the codesandbox. I did some poking around and the root of the problem seems to be because of the change to no longer conditionally render the Modal. Since the Modal sticks around, the FocusScope never unmounts, meaning its focus containment logic is still active even when the Modal is closed. Additionally, Transition doesn't seem to render anything if `show` is false, resulting in the active scope array containing no elements since there aren't any elements [between the scope sentinels](https://github.com/adobe/react-spectrum/blob/e50dc5866c85e5e4015802bec32f1fc24f7f138e/packages/%40react-aria/focus/src/FocusScope.tsx#L115-L125):
<img width="286" alt="image" src="https://github.com/adobe/react-spectrum/assets/9661127/f4e13693-bf53-4ff2-8eed-897a1b019ef3">


Even without the focus containment break, this pattern of always rendering a Modal is currently problematic since it breaks focus restoration back to the modal's trigger when the Modal closes since the FocusScope never unmounts and thus its [restore focus logic won't get run](https://github.com/adobe/react-spectrum/blob/e50dc5866c85e5e4015802bec32f1fc24f7f138e/packages/%40react-aria/focus/src/FocusScope.tsx#L619-L662). I'm not familiar enough with the Headless UI transition stuff to know if it can work with a conditionally rendered Modal off the top of my head, but if you are open to an alternative solution you can check out React Aria Components. We have an [example](https://reactspectrum.blob.core.windows.net/reactspectrum/f239d0b1a96c3e6119135fe6bbf1994dc9984257/verdaccio/rac-tailwind/index.html) of transitions with Tailwind CSS (try clicking the "open dialog" button), more info on that can be found [here](https://react-spectrum.adobe.com/react-aria/react-aria-components.html#examples) along side the code powering that [example](https://github.com/adobe/react-spectrum/blob/main/examples/rac-tailwind/src/App.js)

**Comment by karimhossenbux** [comment]
Thank you very much @LFDanLu for the detailed explanation!
I'll try to replicate your tailwind example from the RAC, and get ride of the Headless UI transition.

Cheers!

**Comment by snowystinger** [comment]
Closing this as resolved. Please let us know if there is still a problem and we can reopen if needed.
