### ISSUE TITLE
Nested DndListBox

### ISSUE THREAD

**Issue by tflanagan** [adobe/react-spectrum#4597]
# 🐛 Bug Report 

I'm attempting to nest `DndListBox`'s with some modifications to the example found in the [Drag between lists](https://react-spectrum.adobe.com/react-aria/ListBox.html#drag-between-lists) section.

I'm able to create the nested objects, and I'm able to reorder the top level list, but the moment I attempt to reorder a nested item, I receive an error. I also cannot target the nested list from the parent list, it just acts like a very large parent item.

## 🤔 Expected Behavior

I expected to be able to move items between nested lists, very similar to the Drag between lists example, just nested within eachother.

Like a folder structure 

## 😯 Current Behavior

```
Uncaught DOMException: Failed to execute 'add' on 'DataTransferItemList': An item already exists for type 'text/plain'.
    at $7252cd45fc48c07c$export$f9c1490890ddd063 (webpack-internal:///../../node_modules/@react-aria/dnd/dist/import.mjs:174:28)
    at onDragStart (webpack-internal:///../../node_modules/@react-aria/dnd/dist/import.mjs:2370:55)
    at eval (webpack-internal:///../../node_modules/@react-aria/utils/dist/import.mjs:216:76)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:4213:16)
    at invokeGuardedCallback (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:4291:25)
    at executeDispatch (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:9073:7)
    at processDispatchQueue (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:9097:3)
    at eval (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:9288:12)
    at batchedUpdates$1 (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26135:12)
    at batchedUpdates (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3991:12)
    at dispatchEventForPluginEventSystem (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:9287:3)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:6465:5)
    at dispatchEvent (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:6457:5)
    at dispatchDiscreteEvent (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:6430:5)
$7252cd45fc48c07c$export$f9c1490890ddd063	                                    @ import.mjs:149
onDragStart	                                                                    @ import.mjs:2345
eval	                                                                            @ import.mjs:171
callCallback	                                                                    @ react-dom.development.js:4164
invokeGuardedCallbackDev	                                                    @ react-dom.development.js:4213
invokeGuardedCallback                                                               @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError                                             @ react-dom.development.js:4291
executeDispatch                                                                     @ react-dom.development.js:9041
processDispatchQueueItemsInOrder                                                    @ react-dom.development.js:9073
processDispatchQueue                                                                @ react-dom.development.js:9086
dispatchEventsForPlugins                                                            @ react-dom.development.js:9097
eval                                                                                @ react-dom.development.js:9288
batchedUpdates$1                                                                    @ react-dom.development.js:26140
batchedUpdates                                                                      @ react-dom.development.js:3991
dispatchEventForPluginEventSystem                                                   @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay     @ react-dom.development.js:6465
dispatchEvent                                                                       @ react-dom.development.js:6457
dispatchDiscreteEvent                                                               @ react-dom.development.js:6430

```

## 💁 Possible Solution

I'm not sure this is an issue with the library. I haven't been able to find an example of this, I did find the [nested drop target example](https://reactspectrum.blob.core.windows.net/reactspectrum/c42fb35488449eeae9fcb38139f02336ad9bc550/storybook/index.html?path=/story/drag-and-drop--nested-drop-regions&providerSwitcher-express=false&providerSwitcher-toastPosition=bottom), so I'm thinking I could do it with the lower level API's.

I'm still navigating the codebase, not sure where to start, I'd be happy to receive advice on where this issue might be

## 🔦 Context

I'm attempting to create a tree of nested items where the items can be freely transitioned between various n-levels of nesting.

Very much like a folder/file tree you see in Windows Explorer when dragging items around

## 💻 Code Sample

[Codepen demo](https://codesandbox.io/s/hopeful-browser-fqrqu7?file=/src/App.js)

Moving the first depth is fine (Adobe Photoshop, Documents, etc), anything deeper triggers the error (Pictures, Notepad, Downloads, VS Code, Home, Videos)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  
| react-aria | ^3.24.0
| react-aria-components | 1.0.0-alpha.3
| react-stately | 3.22.0
| Browser          | Chrome
| Operating System | Win 10 / WSL2 Debian Bullseye

**Comment by tflanagan** [comment]
I found that it is trying to drag both the nested item and the container. Not sure where, but essentially I think I need a "stopPropagation"

**Comment by tflanagan** [comment]
Updated with the [codepen demo](https://codesandbox.io/s/hopeful-browser-fqrqu7?file=/src/App.js)

**Comment by LFDanLu** [comment]
Looks like the error is coming from `writeToDataTransfer` here https://github.com/adobe/react-spectrum/blob/4348bb81b902b5ab61cc0f3bc623d81f6b4d6b0f/packages/%40react-aria/dnd/src/useDrag.ts#L111-L112, a `stopPropagation` before in that drag start could definitely resolve it.

**Comment by tflanagan** [comment]
@LFDanLu Thanks for the help in narrowing that down. I submitted a PR.

I believe the placement of this to be correct, in testing it resolves my problem.
