### ISSUE TITLE
Cannot build repository

### ISSUE THREAD

**Issue by levrik** [adobe/react-spectrum#6582]
### Provide a general summary of the issue here

I would like to contribute a bug fix but cannot run the repository.

### 🤔 Expected Behavior?

Things to build fine

### 😯 Current Behavior

After cloning, running `yarn install` and `yarn start` I am presented with the following error:

```
🚨 Build failed.

@parcel/transformer-postcss: Cannot read properties of undefined (reading 'ending')

  TypeError: Cannot read properties of undefined (reading 'ending')
      at Duplexify.end (/Users/levrik/code/opensource/react-spectrum/node_modules/duplexify/index.js:230:28)
      at Duplexify.setWritable (/Users/levrik/code/opensource/react-spectrum/node_modules/duplexify/index.js:89:10)
      at Pumpify.setPipeline (/Users/levrik/code/opensource/react-spectrum/node_modules/pumpify/index.js:51:10)
      at new Pumpify (/Users/levrik/code/opensource/react-spectrum/node_modules/pumpify/index.js:15:30)
      at Function.Pumpify [as obj] (/Users/levrik/code/opensource/react-spectrum/node_modules/pumpify/index.js:13:44)
      at globStream (/Users/levrik/code/opensource/react-spectrum/node_modules/@spectrum-css/component-builder/node_modules/glob-stream/index.js:73:18)
      at Gulp.src (/Users/levrik/code/opensource/react-spectrum/node_modules/@spectrum-css/component-builder/node_modules/vinyl-fs/lib/src/index.js:24:5)
      at /Users/levrik/code/opensource/react-spectrum/node_modules/@spectrum-css/component-builder/css/lib/varUtils.js:158:10
      at new Promise (<anonymous>)
      at Object.getAllComponentVars (/Users/levrik/code/opensource/react-spectrum/node_modules/@spectrum-css/component-builder/css/lib/varUtils.js:155:10)
```

I already wiped `node_modules` and re-installed from scratch. Also couldn't find anything similar reported on Parcel repo so I'm starting here. Maybe this error has been seen already by a team member?

### 🖥️ Steps to Reproduce

Only seems to happen on my machine

### Version

main

### What browsers are you seeing the problem on?

Other

### What operating system are you using?

macOS 14.5 on M1

**Comment by levrik** [comment]
After a few tries the command doesn't even start anymore and I'm just presented with this:

```
libc++abi: terminating due to uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
```

**Comment by snowystinger** [comment]
what version of node are you using? can you try 18.20.3 if you aren't using that already?
You will probably want to pull the repo down brand new if you try that. At the very least you'll want to clear node_modules.

**Comment by levrik** [comment]
I'm on 18.20.3 already. Repo was freshly pulled for the first time. Just tried restarting my Mac which also didn't help. I'll try to clear some more caches.

**Comment by levrik** [comment]
`yarn cache clean` and then a re-install fixed the issues. Thanks for your help though. I'll be closing this issue now.
